config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    # 名前は必須入力かつ20文字以内
    validates :name, length: {maximum: 20}, presence: true
    # 内容は必須入力かつ2文字以上30文字以下
    validates :body, length: {minimum: 2, maximum: 30}, presence: true
    # 年齢は必須入力かつ0歳以上~150以下の数値
    validates_numericality_of :age, only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 150

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  
  def index
    # Messageを全て取得する
    @messages = Message.all
    @message = Message.new
  end
    
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページヘリダイレクト
      redirect_to root_path, notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は画面編集へ戻す
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
private

  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  
  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <!-- hoge -->
  <meta charset="utf-8">
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="application.css">
</head>
<body class="container msg-body">
    <div class="msg-flame">
        <header>
            <h1>Message Board</h1>
        </header>
        <session>
            <hr class="msg-separator" role="separator" aria-hidden="true">
            
            <%= yield %>
            
            <hr class="msg-separator" role="separator" aria-hidden="true">
        </session>
        <footer>
            <p>&copy; 2015 Toshihiro Chida</p>
        </footer>
    </div>
</body>
</html>

app/views/messages/_form.html.erb
<!-- フォーム入力 -->
<%= form_for(@message, :html => {:class => "msg-flame-form"}) do |f| %>
    <% if @message.errors.present? %>
        <div class="alert alert-danger">
            <%= alert %>
            <ul>
                <% @message.errors.full_messages.each do |full_message| %>
                    <li>
                        <%= full_message %>
                    </li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div>
        <%= f.text_area(:body, :class => "msg-form-textarea", :placeholder => "Message") %>
    </div>
    <div align="right">
        <%= f.text_field(:name, :class => "msg-form-text", :placeholder => "Name") %>
        <%= f.text_field(:age, :class => "msg-form-text", :placeholder => "Age") %>
        <%= f.submit("Send", :class => "btn btn-primary btn-sm msg-form-btn") %>
    </div>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<!-- TimeLine表示 -->
<% if(@messages.length == 0) then %>
    <!-- メッセージ件数0件処理 -->
    <span class="msg-list-group-item-textarea">no message</span>
<% else %>
    <div class="panel panel-default msg-panel">
        <div class="list-group">
            <% @messages.each do |message| %>
                <div class="list-group-item msg-list-group-item">
                     <div class="msg-list-group-item-header">
                        <div class="msg-list-group-item-header-left">
                            <span class="list-group-item-text msg-list-group-item-text"><%= message.name %></span>
                            &nbsp;&nbsp;<span class="list-group-item-text msg-list-group-item-age"><%= message.age %>year old</span>
                        </div>
                        <div class="msg-list-group-item-header-right">
                            <%= link_to "edit", edit_message_path(message) %>
                            <%= link_to "destroy", message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
                        </div>
                    </div>

                    <div class="msg-list-group-item-textarea">
                        <%= simple_format(h(message.body)) %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

<hr  class="msg-separator" role="separator" aria-hidden="true">

<% #部分テンプレートを読み込んでいる %>
<%= render 'form' %>